name: Release

on:
  push:
    branches: [main]

jobs:
  build_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the latest tag
        id: get_tag
        run: echo "latest_tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Zip the extension file
        run: zip -qq -r markdown-tools.zip ./markdown-tools
        working-directory: .

      - uses: actions/upload-artifact@v4
        with:
          name: ext
          path: ./markdown-tools.zip

  publish_release:
    needs: [build_zip]
    runs-on: ubuntu-latest
    steps:
      - name: Download extension
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.latest_tag }}
          token: ${{ secrets.ACCESS_TOKEN }}
          files: |
            ext/markdown-tools.zip