name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build_zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the extension file
        run: zip -qq -r markdown-tools.zip ./markdown-tools
        working-directory: .

      - uses: actions/upload-artifact@v4
        with:
          name: ext
          path: ./markdown-tools.zip

  publish_release:
    needs: [build_zip]
    runs-on: ubuntu-latest
    steps:
      - name: Download extension
        uses: actions/download-artifact@v4

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            markdown-tools.zip